package org.example.jpastudent.controller;

import org.example.jpastudent.model.Student;
import org.example.jpastudent.repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Optional;

@RestController
public class StudentRestController {

    @Autowired
    StudentRepository studentRepository;

    @GetMapping("/addstudent")
    public List<Student> addStudent(){
        Student student = new Student();
        student.setBornDate(LocalDate.now());
        student.setBornTime(LocalTime.now());
        List<Student> list = studentRepository.findAll();
        student.setName("Autogenerated sz=" + list.size());
        studentRepository.save(student);
        return studentRepository.findAll();
    }

    @GetMapping("/students")
    public List<Student> students() {
        var obj = studentRepository.findAll();
        return obj;
    }

    @PostMapping("/student")
    @ResponseStatus(HttpStatus.CREATED)
    public Student addStudent(@RequestBody Student student) {
        System.out.println(student);
        return studentRepository.save(student);
    }

    @GetMapping("/student/{name}")
    public List<Student> findByName(@PathVariable String name) {
        return studentRepository.findAllByName(name);
    }


    @PutMapping("/student/{id}")
    public ResponseEntity<Student> changeStudent(@PathVariable int id, @RequestBody Student student){
        Optional<Student> orgStudent = studentRepository.findById(id);
        if (orgStudent.isPresent()){
            student.setId(orgStudent.get().getId());
            studentRepository.save(student);
            return ResponseEntity.ok(student);
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    @DeleteMapping("/student/{id}")
    public ResponseEntity<String> deleteStudent(@PathVariable int id){
        Optional<Student> orgStudent = studentRepository.findById(id);
        if (orgStudent.isPresent()){
            studentRepository.deleteById(id);
            return ResponseEntity.ok("Student deleted succesfully");
        } else {
            return ResponseEntity.notFound().build();
        }
    }

}

